from models import Certificate, Education, Experience, Profile, Project, Skill

IMAGE_FIELDS = {
    "profile_image": {"subdir": "images", "store": "filename"},
    "logo": {"subdir": "images", "store": "filename"},
    "image": {"subdir": "images/projects", "store": "filename"},
    "image_path": {"subdir": "images", "store": "static_url"},
}

ICON_FIELDS = {"hero_icon", "icon", "bgIcon"}
STYLE_FIELDS = {"iconColor", "bgColor", "hoverColor"}
FIELD_GROUPS = {
    "profile": [
        ("Profile", ["full_name", "title", "tagline", "cv_subtitle", "about"]),
        ("Contact",
         ["email", "phone", "address", "linkedin_url", "github_url", "website_url", "location", "availability_text",
          "contact_intro"]),
        ("Media", ["profile_image"]),
        ("Icon", ["hero_icon"]),
    ],
    "experience": [
        ("Core",
         ["id", "company", "role", "period", "brief", "location", "type", "current", "sort_order", "is_visible"]),
        ("Details", ["details", "tech_stack", "timeline", "skills"]),
        ("Media", ["logo"]),
        ("Icon", ["icon", "bgIcon"]),
        ("Colour customisation", ["iconColor", "bgColor", "hoverColor"]),
    ],
    "education": [
        ("Core", ["id", "degree", "university", "year", "description", "current", "status", "progress", "sort_order",
                  "is_visible"]),
        ("Modules & results", ["stages", "total_credits", "gpa", "modules_completed"]),
        ("Media", ["logo"]),
    ],
    "skills": [
        ("Core", ["id", "title", "desc", "tags", "progress", "stats", "sort_order", "is_visible"]),
        ("Icon", ["icon"]),
        ("Colour customisation", ["iconColor", "bgColor"]),
    ],
    "projects": [
        ("Core", ["id", "title", "desc", "status", "tags", "links", "stats", "features", "challenges", "sort_order",
                  "is_visible"]),
        ("Media", ["image"]),
        ("Icon", ["icon"]),
        ("Colour customisation", ["iconColor", "bgColor"]),
    ],
    "certificates": [
        ("Core", ["id", "title", "issuer", "date", "desc", "link", "credential_id", "skills", "verified", "sort_order",
                  "is_visible"]),
        ("Media", ["image_path", "logo"]),
    ],
}

ICON_CHOICES = [
    ("fas fa-terminal", "Terminal"),
    ("fas fa-code", "Code"),
    ("fas fa-laptop-code", "Developer"),
    ("fas fa-folder", "Folder"),
    ("fas fa-bolt", "Energy"),
    ("fas fa-cogs", "Settings"),
    ("fas fa-gamepad", "Game"),
    ("fas fa-cloud", "Cloud"),
    ("fas fa-flask", "Research"),
    ("fas fa-university", "Education"),
    ("fas fa-building", "Company"),
    ("fas fa-briefcase", "Briefcase"),
    ("fas fa-store", "Store"),
    ("fas fa-wine-bottle", "Retail"),
    ("fas fa-award", "Award"),
    ("fas fa-certificate", "Certificate"),
    ("fas fa-calendar", "Calendar"),
    ("fas fa-chart-line", "Growth"),
    ("fas fa-database", "Database"),
    ("fas fa-server", "Server"),
    ("fas fa-shield-alt", "Security"),
    ("fab fa-python", "Python"),
    ("fab fa-java", "Java"),
    ("fab fa-react", "React"),
    ("fab fa-github", "GitHub"),
]

STYLE_CHOICES = {
    "iconColor": [
        ("text-gray-600", "Graphite"),
        ("text-brand-accent", "Accent"),
        ("text-blue-600", "Blue"),
        ("text-indigo-600", "Indigo"),
        ("text-emerald-500", "Emerald"),
        ("text-green-600", "Green"),
        ("text-orange-600", "Orange"),
        ("text-red-600", "Red"),
        ("text-purple-600", "Purple"),
        ("text-rose-500", "Rose"),
    ],
    "bgColor": [
        ("bg-gray-100", "Graphite"),
        ("bg-brand-accent/10", "Accent"),
        ("bg-blue-100", "Blue"),
        ("bg-indigo-100", "Indigo"),
        ("bg-emerald-100", "Emerald"),
        ("bg-green-100", "Green"),
        ("bg-orange-100", "Orange"),
        ("bg-red-100", "Red"),
        ("bg-purple-100", "Purple"),
        ("bg-rose-100", "Rose"),
    ],
    "hoverColor": [
        ("text-gray-900", "Graphite"),
        ("text-brand-accent", "Accent"),
        ("text-blue-600", "Blue"),
        ("text-indigo-600", "Indigo"),
        ("text-emerald-500", "Emerald"),
        ("text-green-600", "Green"),
        ("text-orange-600", "Orange"),
        ("text-red-600", "Red"),
        ("text-purple-600", "Purple"),
        ("text-rose-500", "Rose"),
        ("group-hover:text-yellow-400", "Hover yellow"),
        ("group-hover:text-green-600", "Hover green"),
    ],
}

SECTIONS = {
    "profile": {
        "label": "Profile",
        "description": "Name, title, contact details, hero copy, and CV header.",
        "model": Profile,
        "singleton": True,
        "fields": [
            ("full_name", "Name", "text"),
            ("title", "Title", "text"),
            ("tagline", "Hero badge", "text"),
            ("cv_subtitle", "CV subtitle", "text"),
            ("about", "About text", "textarea"),
            ("email", "Email", "text"),
            ("phone", "Phone", "text"),
            ("address", "Address", "text"),
            ("linkedin_url", "LinkedIn URL", "text"),
            ("github_url", "GitHub URL", "text"),
            ("website_url", "Website URL", "text"),
            ("location", "Location", "text"),
            ("availability_text", "Contact badge", "text"),
            ("contact_intro", "Contact intro", "textarea"),
            ("profile_image", "Profile image filename", "text"),
            ("hero_icon", "Hero icon", "text"),
        ],
        "title_field": "full_name",
    },
    "experience": {
        "label": "Experience",
        "description": "Companies, roles, job history, timeline entries, bullets, and tech stack.",
        "model": Experience,
        "fields": [
            ("id", "Slug ID", "text"),
            ("company", "Company", "text"),
            ("role", "Role", "text"),
            ("period", "Period", "text"),
            ("brief", "Brief", "textarea"),
            ("details", "Bullet points", "json"),
            ("tech_stack", "Tech stack", "json"),
            ("timeline", "Job timeline / promotions", "json"),
            ("skills", "Skills", "json"),
            ("logo", "Logo filename", "text"),
            ("location", "Location", "text"),
            ("type", "Work type", "text"),
            ("icon", "Icon", "text"),
            ("bgIcon", "Background icon", "text"),
            ("iconColor", "Icon colour", "text"),
            ("bgColor", "Background colour", "text"),
            ("hoverColor", "Hover colour", "text"),
            ("current", "Current role", "checkbox"),
            ("sort_order", "Sort order", "integer"),
            ("is_visible", "Visible", "checkbox"),
        ],
        "title_field": "company",
    },
    "education": {
        "label": "Education",
        "description": "Degrees, colleges, modules, stages, progress, and results.",
        "model": Education,
        "fields": [
            ("id", "Slug ID", "text"),
            ("degree", "Degree", "text"),
            ("university", "University", "text"),
            ("year", "Year", "text"),
            ("logo", "Logo filename", "text"),
            ("description", "Description", "textarea"),
            ("stages", "Stages and modules", "json"),
            ("progress", "Progress percentage", "integer"),
            ("current", "Current", "checkbox"),
            ("status", "Status", "text"),
            ("total_credits", "Total credits", "integer"),
            ("gpa", "GPA / result", "text"),
            ("modules_completed", "Modules completed", "integer"),
            ("sort_order", "Sort order", "integer"),
            ("is_visible", "Visible", "checkbox"),
        ],
        "title_field": "degree",
    },
    "skills": {
        "label": "Skills",
        "description": "Skill groups, tags, progress bars, and card stats.",
        "model": Skill,
        "fields": [
            ("id", "Slug ID", "text"),
            ("title", "Title", "text"),
            ("desc", "Description", "textarea"),
            ("icon", "Icon", "text"),
            ("iconColor", "Icon colour", "text"),
            ("bgColor", "Background colour", "text"),
            ("tags", "Tags", "json"),
            ("progress", "Progress", "json"),
            ("stats", "Stats", "json"),
            ("sort_order", "Sort order", "integer"),
            ("is_visible", "Visible", "checkbox"),
        ],
        "title_field": "title",
    },
    "projects": {
        "label": "Projects",
        "description": "Portfolio projects, links, screenshots, status, features, and tags.",
        "model": Project,
        "fields": [
            ("id", "Slug ID", "text"),
            ("title", "Title", "text"),
            ("desc", "Description", "textarea"),
            ("status", "Status", "text"),
            ("icon", "Icon", "text"),
            ("iconColor", "Icon colour", "text"),
            ("bgColor", "Background colour", "text"),
            ("tags", "Tags", "json"),
            ("links", "Links", "json"),
            ("stats", "Stats", "json"),
            ("features", "Features", "json"),
            ("challenges", "Challenges", "textarea"),
            ("image", "Image filename", "text"),
            ("sort_order", "Sort order", "integer"),
            ("is_visible", "Visible", "checkbox"),
        ],
        "title_field": "title",
    },
    "certificates": {
        "label": "Certificates",
        "description": "Certificates, issuers, dates, credential links, and related skills.",
        "model": Certificate,
        "fields": [
            ("id", "Slug ID", "text"),
            ("title", "Title", "text"),
            ("issuer", "Issuer", "text"),
            ("date", "Date", "text"),
            ("desc", "Description", "textarea"),
            ("image_path", "Image URL/path", "text"),
            ("logo", "Logo filename", "text"),
            ("link", "Credential link", "text"),
            ("credential_id", "Credential ID", "text"),
            ("skills", "Skills", "json"),
            ("verified", "Verified", "checkbox"),
            ("sort_order", "Sort order", "integer"),
            ("is_visible", "Visible", "checkbox"),
        ],
        "title_field": "title",
    },
}

DOCUMENT_SECTION_CONFIG = [
    {
        "key": "experience",
        "label": "Experience",
        "description": "Roles, promotions, bullet points, and work history.",
        "max_items": 3,
        "overflow_warning": "Choose up to 3 employers. Every role and bullet is checked against the one-page limit.",
    },
    {
        "key": "projects",
        "label": "Projects",
        "description": "Selected portfolio projects, descriptions, and technology tags.",
        "max_items": 2,
        "overflow_warning": "Choose up to 2 projects so every selected detail remains readable on one A4 page.",
    },
    {
        "key": "skills",
        "label": "Skills",
        "description": "Skill groups used to build the CV skill tags.",
        "max_items": 3,
        "overflow_warning": "Choose up to 3 focused skill groups to keep the skills column readable.",
    },
    {
        "key": "education",
        "label": "Education",
        "description": "Degrees, modules, stages, and results.",
        "max_items": 2,
        "overflow_warning": "Choose up to 2 education entries so module names are never clipped.",
    },
    {
        "key": "certificates",
        "label": "Certificates",
        "description": "Certificates, issuers, dates, and credentials.",
        "max_items": 3,
        "overflow_warning": "Choose up to 3 relevant certificates for the one-page CV.",
    },
]

ALLOWED_RESUME_TEMPLATE_TARGETS = {
    "resume_summary": "Introduction",
    "company_details": "What I bring",
    "resume_conclusion": "Conclusion",
}

RESUME_SENTENCE_TEMPLATES = [
    {
        "target": "resume_summary",
        "label": "Software role intro",
        "text": "I am writing to apply for the {role} position at {company}. As a Computing and IT student with hands-on software development experience, I am eager to contribute to your team while continuing to grow as a developer.",
    },
    {
        "target": "resume_summary",
        "label": "Testing focus",
        "text": "I am particularly interested in {company} because the role aligns with my experience in backend development, testing, documentation, and building reliable software with a practical user focus.",
    },
    {
        "target": "resume_summary",
        "label": "Graduate tone",
        "text": "As an Open University Computing and IT student, I bring a mix of academic learning, self-directed project work, and real workplace experience that would let me contribute quickly to {company}.",
    },
    {
        "target": "company_details",
        "label": "Python strength",
        "text": "Proficient in Python, with practical experience using Flask, SQL, APIs, and automation to build maintainable software.",
    },
    {
        "target": "company_details",
        "label": "Frontend/backend",
        "text": "Comfortable working across backend and frontend code, including Flask, FastAPI, React, TypeScript, HTML, CSS, and database-backed applications.",
    },
    {
        "target": "company_details",
        "label": "Agile/testing",
        "text": "Practical understanding of Agile workflows, sprint planning, documentation, integration testing, and collaborating in technical teams.",
    },
    {
        "target": "company_details",
        "label": "Communication",
        "text": "Strong communication and teamwork skills developed through academic group projects, internships, and customer-facing work experience.",
    },
    {
        "target": "company_details",
        "label": "Learning mindset",
        "text": "Quick to learn new tools and frameworks, with a steady approach to debugging, documentation, and improving existing systems.",
    },
    {
        "target": "resume_conclusion",
        "label": "Standard close",
        "text": "Thank you for considering my application. I would welcome the opportunity to discuss how my skills, motivation, and experience could support {company}.\n\nYours sincerely,\n\nCiaran Cairns",
    },
    {
        "target": "resume_conclusion",
        "label": "Engineering close",
        "text": "I would be excited to support your engineering team, learn from experienced developers, and contribute to high-quality, reliable software at {company}.\n\nYours sincerely,\n\nCiaran Cairns",
    },
]

RESUME_ROLE_PRESETS = [
    {
        "label": "Software Developer",
        "header_subtitle": "Software Developer Application",
        "target_role": "Software Developer",
        "resume_keywords": "Python, Flask, SQL, APIs, JavaScript, testing",
        "resume_summary": "I am writing to apply for the {role} position at {company}. I bring practical experience building database-backed web applications, APIs, and automation tools, alongside my BSc Computing and IT studies.",
        "company_details": "Experience building maintainable Flask and Python applications with SQL-backed data.\nComfortable working across frontend and backend code, including HTML, CSS, JavaScript, TypeScript, and REST APIs.\nUsed to debugging issues carefully, documenting decisions, and improving existing systems.",
        "resume_conclusion": "I would welcome the opportunity to discuss how my software development experience, motivation, and practical project work could support {company}.\n\nYours sincerely,\n\nCiaran Cairns",
    },
    {
        "label": "QA / Test Engineer",
        "header_subtitle": "QA / Test Engineer Application",
        "target_role": "QA / Test Engineer",
        "resume_keywords": "Testing, debugging, documentation, APIs, Agile, SQL",
        "resume_summary": "I am writing to apply for the {role} position at {company}. I am interested in quality-focused engineering and bring hands-on experience testing, debugging, documenting, and improving software projects.",
        "company_details": "Practical understanding of integration testing, API validation, edge cases, and clear bug reporting.\nExperience working with Python, Flask, SQL, Git, and Agile-style project delivery.\nStrong attention to detail from combining academic projects with real workplace software tasks.",
        "resume_conclusion": "I would be excited to help {company} deliver reliable, well-tested software while continuing to grow my engineering skills.\n\nYours sincerely,\n\nCiaran Cairns",
    },
    {
        "label": "Backend Developer",
        "header_subtitle": "Backend Developer Application",
        "target_role": "Backend Developer",
        "resume_keywords": "Python, Flask, FastAPI, MySQL, REST APIs, Docker",
        "resume_summary": "I am writing to apply for the {role} position at {company}. My strongest experience is in backend development, including Python services, Flask applications, SQL databases, and API-driven workflows.",
        "company_details": "Built and maintained backend features using Python, Flask, MySQL, and structured data models.\nComfortable designing practical APIs, handling validation, and connecting frontend workflows to database-backed systems.\nInterested in writing clear, maintainable code that is easy to support and extend.",
        "resume_conclusion": "I would welcome the opportunity to bring my backend development experience and steady problem-solving approach to {company}.\n\nYours sincerely,\n\nCiaran Cairns",
    },
    {
        "label": "Placement / Internship",
        "header_subtitle": "Placement / Internship Application",
        "target_role": "Placement Software Developer",
        "resume_keywords": "Learning mindset, Python, teamwork, Agile, documentation",
        "resume_summary": "I am writing to apply for the {role} opportunity at {company}. As a Stage 2 BSc Computing and IT student, I am keen to apply my software development skills in a professional team and learn from experienced engineers.",
        "company_details": "Strong foundation in programming, databases, web development, and software engineering principles.\nPractical project experience using Python, Flask, Java, TypeScript, Git, and documentation-led development.\nMotivated, reliable, and quick to learn new tools, with a collaborative approach to team work.",
        "resume_conclusion": "Thank you for considering my application. I would be grateful for the chance to discuss how I could contribute to {company} during a placement or internship.\n\nYours sincerely,\n\nCiaran Cairns",
    },
]

FIELD_HELP = {
    "id": "Leave blank when creating a new item and a slug will be generated automatically.",
    "sort_order": "Lower numbers appear first. Leave blank to place new items at the end.",
    "is_visible": "Untick to hide this item from the public site and PDF without deleting it.",
    "details": "Bullet points for a single job/role.",
    "timeline": "Use this when one company has multiple jobs or promotions.",
    "stages": "Education stages with module lists.",
    "links": "Buttons shown on project cards and modals.",
    "tags": "Short labels such as languages, tools, or topics.",
    "skills": "Short labels used on certificate and experience cards.",
    "stats": "Small facts shown on cards, such as year or project count.",
    "progress": "Optional progress object used by skill and education cards.",
}

JSON_EXAMPLES = {
    "details": [
        "Built a Flask admin tool backed by MySQL.",
        "Improved page speed and accessibility across the portfolio.",
    ],
    "tech_stack": ["Python", "Flask", "MySQL", "HTMX"],
    "timeline": [
        {
            "role": "Software Developer",
            "period": "Jan 2026 - Present",
            "loc": "Remote",
            "desc": "Building production Flask features and maintaining database-backed content.",
        }
    ],
    "skills": ["Python", "Flask", "MySQL"],
    "tags": ["Python", "Flask", "MySQL"],
    "links": [
        {
            "icon": "fab fa-github",
            "url": "https://github.com/username/project",
            "label": "GitHub",
        }
    ],
    "stats": [{"icon": "fas fa-calendar", "value": "2026", "label": "Year"}],
    "features": ["Login-protected admin", "Generated one-page PDF CV"],
    "progress": {"label": "Experience", "value": 3, "unit": "years", "max": 5},
    "stages": {
        "Stage 1": [
            {"code": "TM111", "title": "Introduction to Computing and IT Part 1"}
        ]
    },
}

JSON_EDITOR_KINDS = {
    "details": "list",
    "tech_stack": "list",
    "skills": "list",
    "tags": "list",
    "features": "list",
    "links": "links",
    "stats": "stats",
    "timeline": "timeline",
    "stages": "stages",
    "progress": "progress",
}
